In [1]:
#-- Check and Print Numpy version (Numerical Python). --#
import numpy as np
print(f"Numpy version: {np.__version__}")

Numpy version: 1.26.4


In [2]:
#-- Import Numpy Library. --#
import numpy as np
#-- Creating NumPy ndarray Object. --#
array = np.array([1,2,3,4,5])
#-- Print the Array. --#
print(f"The sample array: {array}")
#-- Print type of the Array. --#
print(f"Type of sample array: {type(array)}")

The sample array: [1 2 3 4 5]
Type of sample array: <class 'numpy.ndarray'>


In [3]:
#-- Dimensions in Array. --#
import numpy as np #-- Import Library. --#
array = np.array(42) #-- One element in the array. --#
print(f"The dimension of {array} is {array.ndim}")
#-- 1D Dimension (Like several house in a range). --#
oned_array = np.array([1, 2, 3, 4, 5]) 
print(f"The dimension of {oned_array} is {oned_array.ndim}")
#-- 2D Dimension (Like the apartment need to know room and floor). --#
twod_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"The dimension of {twod_array} is {twod_array.ndim}")
#-- 3D Dimension. --#
threed_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(f"The dimension of {threed_array} is {threed_array.ndim}")
#- Check dimension of the array. --#
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(f"The dimension of {d} is {d.ndim}")
#-- Higher Dimensions. --#
high_demsion_array = np.array([1, 2, 3, 4], ndmin=5)
print(high_demsion_array)
print('number of dimensions :', high_demsion_array.ndim)

The dimension of 42 is 0
The dimension of [1 2 3 4 5] is 1
The dimension of [[1 2 3]
 [4 5 6]] is 2
The dimension of [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] is 3
The dimension of [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] is 3
[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [4]:
#-- NumPy Array Indexing. --#
arr = np.array([1,2,3,4,5])
for i,num in enumerate(arr):
    print(f"The {i} element of {arr} is {num}")
#-- Accessing 2-D Arrays. --#
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('The 2nd element on 1st row: ', arr[0, 1]) #-- Row First, Column After. --#
#-- Accessing 3-D Arrays. --#
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('The second element of the first array in the first block',arr[0, 1, 2])
#-- Negative Indexing. --#
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


The 0 element of [1 2 3 4 5] is 1
The 1 element of [1 2 3 4 5] is 2
The 2 element of [1 2 3 4 5] is 3
The 3 element of [1 2 3 4 5] is 4
The 4 element of [1 2 3 4 5] is 5
The 2nd element on 1st row:  2
The second element of the first array in the first block 6
Last element from 2nd dim:  10


In [15]:
#-- Array Slicing. --#
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr[1:5]) #-- Print staring from element 1 to 4. --#
print(arr[4:]) #-- Print starting from element 4 to the end of the list. --#
print(arr[-3:-1])
print(arr[1:10:2])
print(arr[::2])
#-- Slicing 2D Arrays. --#
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])

[2 3 4 5]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[18 19]
[ 2  4  6  8 10]
[ 1  3  5  7  9 11 13 15 17 19]
[7 8 9]
[3 8]


In [ ]:
#-- Checking Data Types. --#
int_arr = np.array([1, 2, 3, 4])
print(f"Data type of the {int_arr} is: {int_arr.dtype}")
string_arr = np.array(['apple', 'banana', 'cherry'])
print(f"Data type of the {string_arr} is: {string_arr.dtype}")
#-- Generating Arrays with Default Data Type. --#
arr01 = np.array([1, 2, 3, 4], dtype='S')
print(f"Data type of {arr01} is: {arr01.dtype}")
arr02 = np.array([1, 2, 3, 4], dtype='i4')
print(f"Data type of {arr02} is: {arr02.dtype}")
#-- Converting Data Types on Existing Arrays. --#
oldarr = np.array([1.1, 2.1, 3.1])
newarr = oldarr.astype('i')
print(f"Data type of {oldarr} is: {oldarr.dtype}")
print(f"Data type of {newarr} is: {newarr.dtype}") #-- In this case, numbers will convert to 1,2,3. --#

Data type of the [1 2 3 4] is: int32
Data type of the ['apple' 'banana' 'cherry'] is: <U6
Data type of [b'1' b'2' b'3' b'4'] is: |S1
Data type of [1 2 3 4] is: int32
Data type of [1.1 2.1 3.1] is: float64
Data type of [1 2 3] is: int32


In [31]:
#-- Array Copy and View. --#
#-- Copy means copy already array and change an element in the new copied array. -#
import numpy as np
array = np.array([1, 2, 3, 4, 5])
newarray = array.copy()
newarray[1] = 25
print(f"The oiginal array is: {array}")
print(f"The updated array is: {newarray}") 
#-- View means see original and then changed directly. --#
odd_numbers = np.array([10, 12, 14, 16, 18])
updated_odd_numbers = odd_numbers.view()
odd_numbers[2] = 24
print(f"The origina: {odd_numbers}")
print(f"The updated: {updated_odd_numbers}")

The oiginal array is: [1 2 3 4 5]
The updated array is: [ 1 25  3  4  5]
The origina: [10 12 24 16 18]
The updated: [10 12 24 16 18]


In [34]:
#-- Shape pf the array. --#
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"The shape of the {arr} is {arr.shape}")
newarr = np.array([1, 2, 3, 4], ndmin=5)
print(newarr)
print('shape of array :', newarr.shape)

The shape of the [[1 2 3 4]
 [5 6 7 8]] is (2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [42]:
#-- Reshape from 1-D to 2-D array. --#
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
#-- Reshape from 1-D to 3-D array. --#
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)
#-- Flattern Array. --#
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]
