In [20]:
#-- Iterating the 1-D Array. --#
print('-' * 35)
import numpy as np
arr = np.array([1, 2, 3])
for i,num in enumerate(arr):
    print(f"The {i} element of the {arr} is {arr[i]}")
print('-' * 35)
#-- Iterating the 2-D Array. --#
array = np.array([[1, 2, 3], [4, 5, 6]])
for x in array:
    print(x)

print('-' * 35)
array01 = array = np.array([[7, 8, 9], [10, 11, 12]])
for num in array01:
    for numbers in num:
        print(numbers)
print('-' * 35)
#-- Iterating the 3-D Array. --#
threed_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for element in threed_array:
    print(element)
print('-' * 35)

threed_array01 = np.array([[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]])
for x in threed_array01:
    for y in x:
        for z in y:
            print(z)
#-- Interating Arrays using nditer(). --#
sample_arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(sample_arr):
    print(x)
#-- Iterating Arrays with Different Data Types. --#
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
#-- Iterating wth Diiferent Step Size. --#
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)
#-- Enumerated Iteration using ndenumrate(). --#
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

-----------------------------------
The 0 element of the [1 2 3] is 1
The 1 element of the [1 2 3] is 2
The 2 element of the [1 2 3] is 3
-----------------------------------
[1 2 3]
[4 5 6]
-----------------------------------
7
8
9
10
11
12
-----------------------------------
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
-----------------------------------
13
14
15
16
17
18
19
20
21
22
23
24
1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
1
3
5
7
(0,) 1
(1,) 2
(2,) 3


In [27]:
#-- Join Array. --#
import numpy as np
array01 = np.array([1, 2, 3])
array02 = np.array([4, 5, 6])
arrayall = np.concatenate((array01, array02))
print(f"The catenate array of {array01} and {array02} is {arrayall} ")
#-- Join 2D Array. --#
twod_array01 = np.array([[1, 2], [3, 4]])
twod_array02 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((twod_array01, twod_array02), axis=1)
print(f"The catenate array of {twod_array01} and {twod_array02} is {arr}")
#-- Join arrays using stack() function. --#
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
#-- Stacking along rows. --#
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
#-- Stacking along columns. --#
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)
#-- Stacking along Height. --#
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)


The catenate array of [1 2 3] and [4 5 6] is [1 2 3 4 5 6] 
The catenate array of [[1 2]
 [3 4]] and [[5 6]
 [7 8]] is [[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [35]:
#-- Split Array. --#
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

array01 = np.array([7, 8, 9, 10, 11, 12])
newarray01 = np.array_split(array01, 4)
print(newarray01)
#-- Split 2-D Arrays. --#
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)
#-- Using hstack(). --#
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([7, 8]), array([ 9, 10]), array([11]), array([12])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [52]:
#-- Searching Array. --#
arr = np.array([1, 2, 3, 4, 5, 100])
x = np.where(arr == 100) #-- Find the element which has value equal to 100. --#
#-- Shows the position of number. --#
print(x)
array = np.array([10, 11, 12, 13, 14, 15, 16])
#-- Find value which devide to 2 is empty. --# 
y = np.where(array%2 == 0)
print(y)
#-- Search Sorted. --#
array01 = np.array([20, 30, 21, 22, 23, 24])
sortedarray = np.sort(array01)
y = np.searchsorted(sortedarray, 22) #-- print the posision of the value 22. --#
print(f"The position of the value 22 in the array is: {y}")
#-- Search from right side. --#
array02 = np.array([6, 7, 8, 9])
x = np.searchsorted(array02, 7, side='right') #-- Start searching from right to left side. --#
print(x)
#-- Multiple Values. --#
array03 = np.array([1, 3, 5, 7])
x = np.searchsorted(array03, [2, 4, 6])
print(x)

(array([5], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)
The position of the value 22 in the array is: 2
2
[1 2 3]


In [56]:
#-- Array Sort. --#
import numpy as np
array = np.array([3, 2, 0, 1])
print(np.sort(array))
stringarr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(stringarr))
booleanarr = np.array([True, False, True])
print(np.sort(booleanarr))
#-- Sorting 2d Array. --#
twod_arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(twod_arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


In [59]:
#-- Array Filter. --#
arr = np.array([41, 42, 43, 44])
filter_arr = [] #-- Create empty list. --#
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

#-- Even elements. --#arr = np.array([1, 2, 3, 4, 5, 6, 7]). --#
numarr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []
for element in numarr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = numarr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
[False, True, False, True, False, True, False]
[2 4 6]
