In [1]:
#-- Check and Print Numpy version (Numerical Python). --#
import numpy as np
print(f"Numpy version: {np.__version__}")

Numpy version: 1.26.4


In [6]:
#-- Import Numpy Library. --#
import numpy as np
#-- Creating NumPy ndarray Object. --#
array = np.array([1,2,3,4,5])
#-- Print the Array. --#
print(f"The sample array: {array}")
#-- Print type of the Array. --#
print(f"Type of sample array: {type(array)}")

The sample array: [1 2 3 4 5]
Type of sample array: <class 'numpy.ndarray'>


In [17]:
#-- Dimensions in Array. --#
import numpy as np #-- Import Library. --#
array = np.array(42) #-- One element in the array. --#
print(f"The dimension of {array} is {array.ndim}")
#-- 1D Dimension (Like several house in a range). --#
oned_array = np.array([1, 2, 3, 4, 5]) 
print(f"The dimension of {oned_array} is {oned_array.ndim}")
#-- 2D Dimension (Like the apartment need to know room and floor). --#
twod_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"The dimension of {twod_array} is {twod_array.ndim}")
#-- 3D Dimension. --#
threed_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(f"The dimension of {threed_array} is {threed_array.ndim}")
#- Check dimension of the array. --#
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(f"The dimension of {d} is {d.ndim}")
#-- Higher Dimensions. --#
high_demsion_array = np.array([1, 2, 3, 4], ndmin=5)
print(high_demsion_array)
print('number of dimensions :', high_demsion_array.ndim)

The dimension of 42 is 0
The dimension of [1 2 3 4 5] is 1
The dimension of [[1 2 3]
 [4 5 6]] is 2
The dimension of [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] is 3
The dimension of [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] is 3
[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
#-- NumPy Array Indexing. --#
arr = np.array([1,2,3,4,5])
for i,num in enumerate(arr):
    print(f"The {i} element of {arr} is {num}")
#-- Accessing 2-D Arrays. --#
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('The 2nd element on 1st row: ', arr[0, 1]) #-- Row First, Column After. --#
#-- Accessing 3-D Arrays. --#
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('The second element of the first array in the first block',arr[0, 1, 2])
#-- Negative Indexing. --#
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


The 0 element of [1 2 3 4 5] is 1
The 1 element of [1 2 3 4 5] is 2
The 2 element of [1 2 3 4 5] is 3
The 3 element of [1 2 3 4 5] is 4
The 4 element of [1 2 3 4 5] is 5
The 2nd element on 1st row:  2
6
Last element from 2nd dim:  10
