# A. Pytorch and Deep learning Fundamentals. #

In [8]:
#-- Import PyTorch Library. --#
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#-- Print PyTorch Version. --#
print(f"Pytorch Version: {torch.__version__}")

Pytorch Version: 2.11.0+cpu


## 1.1 Introduction to Tensors. ##

### Generating Tensors. ###

In [15]:
#-- Scalar (No Dimension - Just only number). --#
scalar = torch.tensor(7)
print(f"Scalar: {scalar}")
print(f"Dimension of {scalar}: {scalar.ndim}")
print(f"Get Tensor back as Python int: {scalar.item()}")

Scalar: 7
Dimension of 7: 0
Get Tensor back as Python int: 7


In [17]:
#-- Vector. --#
vector = torch.tensor([7, 7])
print(f"Vector: {vector}")
print(f"Dimension of {vector}: {vector.ndim}")
print(f"Shape of the {vector}: {vector.shape}")

Vector: tensor([7, 7])
Dimension of tensor([7, 7]): 1
Shape of the tensor([7, 7]): torch.Size([2])


In [21]:
#-- Matrix. --#
MATRIX = torch.tensor([[7, 8],
                       [9, 1]])
print(f"Matrix: {MATRIX}")
print(f"Dimension of {MATRIX}: {MATRIX.ndim}")
print(f"Shape of the {MATRIX}: {MATRIX.shape}")
print(f"The second row of {MATRIX} is: {MATRIX[1]}")

Matrix: tensor([[7, 8],
        [9, 1]])
Dimension of tensor([[7, 8],
        [9, 1]]): 2
Shape of the tensor([[7, 8],
        [9, 1]]): torch.Size([2, 2])
The second row of tensor([[7, 8],
        [9, 1]]) is: tensor([9, 1])


In [27]:
#-- TENSOR. --#
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(f"Tensor: {TENSOR}")
print(f"Dimension of {TENSOR}: {TENSOR.ndim}")
print(f"Shape of the {TENSOR}: {TENSOR.shape}")
TENSOR[0]

Tensor: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Dimension of tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]): 3
Shape of the tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]): torch.Size([1, 3, 3])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors. ###

Why random tensors?

Random tensor are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.


In [31]:
#-- Generate a random tensor of size (1, 10, 4). --#
random_tensor = torch.rand(1, 5, 4)
print(f"Random Tensor: {random_tensor}")
print(f"Dimension of {random_tensor}: {random_tensor.ndim}")
print(f"Shape of the {random_tensor}: {random_tensor.shape}")

Random Tensor: tensor([[[0.3548, 0.8953, 0.9473, 0.8714],
         [0.5355, 0.7155, 0.7078, 0.7501],
         [0.1806, 0.3525, 0.5259, 0.9939],
         [0.1348, 0.7841, 0.3509, 0.4400],
         [0.1369, 0.7906, 0.3985, 0.8586]]])
Dimension of tensor([[[0.3548, 0.8953, 0.9473, 0.8714],
         [0.5355, 0.7155, 0.7078, 0.7501],
         [0.1806, 0.3525, 0.5259, 0.9939],
         [0.1348, 0.7841, 0.3509, 0.4400],
         [0.1369, 0.7906, 0.3985, 0.8586]]]): 3
Shape of the tensor([[[0.3548, 0.8953, 0.9473, 0.8714],
         [0.5355, 0.7155, 0.7078, 0.7501],
         [0.1806, 0.3525, 0.5259, 0.9939],
         [0.1348, 0.7841, 0.3509, 0.4400],
         [0.1369, 0.7906, 0.3985, 0.8586]]]): torch.Size([1, 5, 4])


In [33]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones ###

In [39]:
#-- Create a tensor of all zeros. --#
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
#-- Create a tensor of all ones. --#
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

In [46]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like. ###

In [56]:
#-- Use torch.range() and get deprecated messgae, use torch.arange(). --#
one_to_ten = torch.arange(start=0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#-- Creating tensors like. --#
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes. ###

Note:  Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [66]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [67]:
float_32_tensor.dtype

torch.float32

In [68]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [71]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [72]:
float_32_tensor = int_32_tensor
float_32_tensor

tensor([3, 6, 9])

### Getting Information with Tensors. ###
1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [73]:
#-- Create a Tensor. --#
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3166, 0.7466, 0.5537, 0.8012],
        [0.9773, 0.8130, 0.2593, 0.2659],
        [0.0460, 0.2773, 0.4937, 0.3328]])

In [75]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [76]:
some_tensor.size()

torch.Size([3, 4])

In [74]:
#-- Find out details about some tensor. --#
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3166, 0.7466, 0.5537, 0.8012],
        [0.9773, 0.8130, 0.2593, 0.2659],
        [0.0460, 0.2773, 0.4937, 0.3328]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations). ###

1. Addition
2. Substraction
3. Multiplication
4. Division
5. Matrix multiplication

In [83]:
#-- Create a tensor and add 10 to it. --#
tensor = torch.tensor([1, 2, 3])
print(f"Tensor {tensor} after adding 10: {tensor + 10}")
#-- Multiply tensor by 10. --#
print(f"Tensor {tensor} after multiplying 10: {tensor * 10}")
#-- Substract tensor by 10. --#
print(f"Tensor {tensor} after subtracting 10: {tensor - 10}")

Tensor tensor([1, 2, 3]) after adding 10: tensor([11, 12, 13])
Tensor tensor([1, 2, 3]) after multiplying 10: tensor([10, 20, 30])
Tensor tensor([1, 2, 3]) after subtracting 10: tensor([-9, -8, -7])


In [89]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")
#-- Matrix Multiplication. --#
torch.matmul(tensor, tensor)
1*1 + 2*2 + 3*3

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


14

In [90]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]
value

CPU times: user 1.37 ms, sys: 886 µs, total: 2.26 ms
Wall time: 10.9 ms


tensor(12)

In [91]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 696 µs, sys: 52 µs, total: 748 µs
Wall time: 572 µs


tensor(14)

### Finding the Min, Mxax, Sum, etc (tensor aggregation) ###

In [102]:
x = torch.arange(0, 100, 10)
#-- Find the Min. --#
print(f"The minimum value of the {tensor} is: {torch.min(x), x.min()}")
#-- Find the Max. --#
print(f"The maximum value of the {tensor} is: {torch.max(x), x.max()}")
#-- Find the Mean. --#
print(f"The mean of {tensor} is: {torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()}")
#-- Find the Suprint(f"The mean of {tensor} is: {torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()}")
print(f"The maximum value of the {tensor} is: {torch.sum(x), x.sum()}")
print(f"The minimum position of the {tensor} is: {torch.argmin(x), x.argmin()}")
print(f"The maximum position of the {tensor} is: {torch.argmax(x), x.argmax()}")
#

The minimum value of the tensor([1, 2, 3]) is: (tensor(0), tensor(0))
The maximum value of the tensor([1, 2, 3]) is: (tensor(90), tensor(90))
The mean of tensor([1, 2, 3]) is: (tensor(45.), tensor(45.))
The maximum value of the tensor([1, 2, 3]) is: (tensor(450), tensor(450))
The minimum position of the tensor([1, 2, 3]) is: (tensor(0), tensor(0))
The maximum position of the tensor([1, 2, 3]) is: (tensor(9), tensor(9))


### Reshaping, Stacking, squeezing, an unsqeezing tensors. ###

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensor on top of other (vstack) or side-by-side (hstack).
* Squeeze -Removes all '1' all dimensions from a tensor
* Unsquueze - add a 1 dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [114]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [115]:
#-- Add an extra dimension. --#
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [116]:
#-- Change the View. --#
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [117]:
#-- Changing z changes x. --#
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [120]:
#-- Stack tensors on top of each other. --#
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [122]:
x_reshaped, x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [123]:
import torch
tensor_3d = torch.tensor([[[1, 2, 3],
                           [4, 5, 6]]])

print("Original Tensor:")
print(tensor_3d)
print(f"Original shape: {tensor_3d.shape}\n")

permuted_tensor = tensor_3d.permute(1, 2, 0)
print("Tensor after permute(1, 2, 0):")
print(permuted_tensor)
print(f"New shape: {permuted_tensor.shape}")

Original Tensor:
tensor([[[1, 2, 3],
         [4, 5, 6]]])
Original shape: torch.Size([1, 2, 3])

Tensor after permute(1, 2, 0):
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])
New shape: torch.Size([2, 3, 1])


### Selecting data (Index). ###

In [124]:
tensor_1d = torch.arange(0, 10)
print("Original vector:", tensor_1d)
print("Shape:", tensor_1d.shape)
print("Index 2:", tensor_1d[2])
print("Slice from 1 to 5:", tensor_1d[1:5])
print("Step = 2:", tensor_1d[::2])

Original vector: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape: torch.Size([10])
Index 2: tensor(2)
Slice from 1 to 5: tensor([1, 2, 3, 4])
Step = 2: tensor([0, 2, 4, 6, 8])


In [125]:
# Create a 3x3 matrix
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

print("Original matrix:\n", tensor_2d)

# Get the 2nd row (index 1)
print("Row at index 1:", tensor_2d[1])

# Get a specific element: Row 0, Column 2 (number 3)
print("Element at [0, 2]:", tensor_2d[0, 2])

# Get all rows, but only column index 1 (the middle column) -> [2, 5, 8]
print("All rows, column 1:", tensor_2d[:, 1])

# Slice the first 2 rows and the first 2 columns
print("Matrix slicing:\n", tensor_2d[:2, :2])

Original matrix:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Row at index 1: tensor([4, 5, 6])
Element at [0, 2]: tensor(3)
All rows, column 1: tensor([2, 5, 8])
Matrix slicing:
 tensor([[1, 2],
        [4, 5]])


In [126]:
tensor_data = torch.tensor([10, 20, 30, 40, 50])

# Create a boolean mask (filter numbers greater than 25)
mask = tensor_data > 25
print("Boolean mask (>25):", mask)

# Use the mask to extract matching values
filtered_data = tensor_data[mask]
print("Values greater than 25:", filtered_data)

# Or write it concisely in a single line:
print("Direct filtering:", tensor_data[tensor_data > 25])

Boolean mask (>25): tensor([False, False,  True,  True,  True])
Values greater than 25: tensor([30, 40, 50])
Direct filtering: tensor([30, 40, 50])


### Reproductbiliyy. ###

In [127]:
import random
import numpy as np
import torch

def set_seed(seed=42):
    # 1. Python random module
    random.seed(seed)

    # 2. NumPy
    np.random.seed(seed)

    # 3. PyTorch (CPU and CUDA)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed) # If using multi-GPU

    # 4. Ensure deterministic behavior in cuDNN backend
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    # 5. Force deterministic algorithms (PyTorch 1.7+)
    torch.use_deterministic_algorithms(True, warn_only=True)

# Call the function before doing any tensor operations or training
set_seed(42)