In [2]:
import pandas as pd
from sklearn.datasets import load_iris
d = load_iris()
df = pd.DataFrame(data=d.data, columns=d.feature_names)
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit_transform(df['petal length (cm)'].values.reshape(-1,1)))

[[-1.34022653]
 [-1.34022653]
 [-1.39706395]
 [-1.2833891 ]
 [-1.34022653]
 [-1.16971425]
 [-1.34022653]
 [-1.2833891 ]
 [-1.34022653]
 [-1.2833891 ]
 [-1.2833891 ]
 [-1.22655167]
 [-1.34022653]
 [-1.51073881]
 [-1.45390138]
 [-1.2833891 ]
 [-1.39706395]
 [-1.34022653]
 [-1.16971425]
 [-1.2833891 ]
 [-1.16971425]
 [-1.2833891 ]
 [-1.56757623]
 [-1.16971425]
 [-1.05603939]
 [-1.22655167]
 [-1.22655167]
 [-1.2833891 ]
 [-1.34022653]
 [-1.22655167]
 [-1.22655167]
 [-1.2833891 ]
 [-1.2833891 ]
 [-1.34022653]
 [-1.2833891 ]
 [-1.45390138]
 [-1.39706395]
 [-1.34022653]
 [-1.39706395]
 [-1.2833891 ]
 [-1.39706395]
 [-1.39706395]
 [-1.39706395]
 [-1.22655167]
 [-1.05603939]
 [-1.34022653]
 [-1.22655167]
 [-1.34022653]
 [-1.2833891 ]
 [-1.34022653]
 [ 0.53540856]
 [ 0.42173371]
 [ 0.64908342]
 [ 0.13754657]
 [ 0.47857113]
 [ 0.42173371]
 [ 0.53540856]
 [-0.26031542]
 [ 0.47857113]
 [ 0.08070915]
 [-0.14664056]
 [ 0.25122143]
 [ 0.13754657]
 [ 0.53540856]
 [-0.08980313]
 [ 0.36489628]
 [ 0.42173

In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
print(scaler.fit_transform(df['petal length (cm)'].values.reshape(-1,1)))

[[0.06779661]
 [0.06779661]
 [0.05084746]
 [0.08474576]
 [0.06779661]
 [0.11864407]
 [0.06779661]
 [0.08474576]
 [0.06779661]
 [0.08474576]
 [0.08474576]
 [0.10169492]
 [0.06779661]
 [0.01694915]
 [0.03389831]
 [0.08474576]
 [0.05084746]
 [0.06779661]
 [0.11864407]
 [0.08474576]
 [0.11864407]
 [0.08474576]
 [0.        ]
 [0.11864407]
 [0.15254237]
 [0.10169492]
 [0.10169492]
 [0.08474576]
 [0.06779661]
 [0.10169492]
 [0.10169492]
 [0.08474576]
 [0.08474576]
 [0.06779661]
 [0.08474576]
 [0.03389831]
 [0.05084746]
 [0.06779661]
 [0.05084746]
 [0.08474576]
 [0.05084746]
 [0.05084746]
 [0.05084746]
 [0.10169492]
 [0.15254237]
 [0.06779661]
 [0.10169492]
 [0.06779661]
 [0.08474576]
 [0.06779661]
 [0.62711864]
 [0.59322034]
 [0.66101695]
 [0.50847458]
 [0.61016949]
 [0.59322034]
 [0.62711864]
 [0.38983051]
 [0.61016949]
 [0.49152542]
 [0.42372881]
 [0.54237288]
 [0.50847458]
 [0.62711864]
 [0.44067797]
 [0.57627119]
 [0.59322034]
 [0.52542373]
 [0.59322034]
 [0.49152542]
 [0.6440678 ]
 [0.50

In [5]:
from sklearn.preprocessing import MaxAbsScaler
scaler = MaxAbsScaler()
print(scaler.fit_transform(df['petal length (cm)'].values.reshape(-1,1)))

[[0.20289855]
 [0.20289855]
 [0.1884058 ]
 [0.2173913 ]
 [0.20289855]
 [0.24637681]
 [0.20289855]
 [0.2173913 ]
 [0.20289855]
 [0.2173913 ]
 [0.2173913 ]
 [0.23188406]
 [0.20289855]
 [0.15942029]
 [0.17391304]
 [0.2173913 ]
 [0.1884058 ]
 [0.20289855]
 [0.24637681]
 [0.2173913 ]
 [0.24637681]
 [0.2173913 ]
 [0.14492754]
 [0.24637681]
 [0.27536232]
 [0.23188406]
 [0.23188406]
 [0.2173913 ]
 [0.20289855]
 [0.23188406]
 [0.23188406]
 [0.2173913 ]
 [0.2173913 ]
 [0.20289855]
 [0.2173913 ]
 [0.17391304]
 [0.1884058 ]
 [0.20289855]
 [0.1884058 ]
 [0.2173913 ]
 [0.1884058 ]
 [0.1884058 ]
 [0.1884058 ]
 [0.23188406]
 [0.27536232]
 [0.20289855]
 [0.23188406]
 [0.20289855]
 [0.2173913 ]
 [0.20289855]
 [0.68115942]
 [0.65217391]
 [0.71014493]
 [0.57971014]
 [0.66666667]
 [0.65217391]
 [0.68115942]
 [0.47826087]
 [0.66666667]
 [0.56521739]
 [0.50724638]
 [0.60869565]
 [0.57971014]
 [0.68115942]
 [0.52173913]
 [0.63768116]
 [0.65217391]
 [0.5942029 ]
 [0.65217391]
 [0.56521739]
 [0.69565217]
 [0.57

In [6]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
print(scaler.fit_transform(df['petal length (cm)'].values.reshape(-1,1)))

[[-0.84285714]
 [-0.84285714]
 [-0.87142857]
 [-0.81428571]
 [-0.84285714]
 [-0.75714286]
 [-0.84285714]
 [-0.81428571]
 [-0.84285714]
 [-0.81428571]
 [-0.81428571]
 [-0.78571429]
 [-0.84285714]
 [-0.92857143]
 [-0.9       ]
 [-0.81428571]
 [-0.87142857]
 [-0.84285714]
 [-0.75714286]
 [-0.81428571]
 [-0.75714286]
 [-0.81428571]
 [-0.95714286]
 [-0.75714286]
 [-0.7       ]
 [-0.78571429]
 [-0.78571429]
 [-0.81428571]
 [-0.84285714]
 [-0.78571429]
 [-0.78571429]
 [-0.81428571]
 [-0.81428571]
 [-0.84285714]
 [-0.81428571]
 [-0.9       ]
 [-0.87142857]
 [-0.84285714]
 [-0.87142857]
 [-0.81428571]
 [-0.87142857]
 [-0.87142857]
 [-0.87142857]
 [-0.78571429]
 [-0.7       ]
 [-0.84285714]
 [-0.78571429]
 [-0.84285714]
 [-0.81428571]
 [-0.84285714]
 [ 0.1       ]
 [ 0.04285714]
 [ 0.15714286]
 [-0.1       ]
 [ 0.07142857]
 [ 0.04285714]
 [ 0.1       ]
 [-0.3       ]
 [ 0.07142857]
 [-0.12857143]
 [-0.24285714]
 [-0.04285714]
 [-0.1       ]
 [ 0.1       ]
 [-0.21428571]
 [ 0.01428571]
 [ 0.04285