In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [11]:
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 1, 0, 1, 1, 1, 1, 1])
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 0 1 0 1 1 1 1 1]


In [12]:
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [13]:
print(model.intercept_)
print(model.coef_)

[-1.11093574]
[[0.55094252]]


In [14]:
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
print(p_pred)
print(y_pred)

[[0.75230352 0.24769648]
 [0.63645097 0.36354903]
 [0.50226266 0.49773734]
 [0.36774761 0.63225239]
 [0.25108493 0.74891507]
 [0.1619518  0.8380482 ]
 [0.10022569 0.89977431]
 [0.06033212 0.93966788]
 [0.03568786 0.96431214]
 [0.02088645 0.97911355]]
[0 0 0 1 1 1 1 1 1 1]


In [16]:
score = model.score(x,y)
print(score)

0.8


In [17]:
conf = confusion_matrix(y, y_pred)
print(conf)

[[2 1]
 [1 6]]


In [18]:
report = classification_report(y, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10

